export default {
  primary: "#455A64",
  secondary: "#8AD7EF",
  fillcolor: "#DCF3F7",
  numberColor: "#7AD3B5",
  white: "#FFFFFF",
  grey: "#939599",
  btnColor: "#0380C7",
  greem: "#19BE86",
  greyLight: "#C4C4C4",
  greymedium: "#A8A8A8",
  greyNormal: "#F4F4F4",
  red: "#EE2D2D",
  black: "#1E2228",
  regular: "Roboto_Regular",
  medium: "Roboto_Medium",
  bold: "Roboto_Bold",
  italic: "Roboto_Italic",
  light: "Roboto_Light",
};
